[theme]
theme = "native"

[icons]
icons = "awesome5"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%A, %b. %e, %Y %T') "

[[block]]
block = "custom"
shell = "bash"
command = "/home/seb/.config/i3status-rust/updates"
format=" $text.str(max_w:4) "
interval = 600

[[block]]
block="net"
device="wlan0"
format=" NET: $ssid "

[[block]]
block = "custom"
shell = "bash"
command = "/home/seb/.config/i3status-rust/battery"
format=" $text.str(max_w:6) "
interval = 4

[[block]]
block = "cpu"
interval = 1
format = " CPU: $utilization "

[[block]]
block = "memory"
format = " MEM: $mem_total_used_percents.eng(w:2) "
